import { ToastContainer } from "react-toastify";
import { barlow, raleway, roboto, ubuntu } from "./font";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
export const metadata = {
  title: "space-tourism | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${raleway.variable} ${barlow.variable} `}
      >
        <Header />
        <main>{children}</main>
        <Footer />
        <ToastContainer
          position="top-center"
          autoClose={1000}
          hideProgressBar={true}
          pauseOnHover
        />
      </body>
    </html>
  );
}
